name: shop
description: E-Commerce Application .
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.6.2
  share_plus: ^6.3.0
  new_version_plus: ^0.0.4
  flutter_launch: ^0.3.0
  photo_view: ^0.14.0
  pinch_zoom: ^1.0.0
  flutter_dialogs: ^2.1.1
  url_launcher:

  dio: ^4.0.6
  flutter_spinkit: ^5.1.0
  multiselect: ^0.0.4
  pull_to_refresh: ^2.0.0
  awesome_dialog: ^3.0.2
  logger: ^1.1.0
  dropdown_button2: ^1.4.0
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  http: ^0.13.4
  multi_select_flutter: ^4.1.2
  bloc: ^8.0.3
  internet_connection_checker: ^0.0.1+3
  shimmer: ^2.0.0
  animated_text_kit: ^4.2.1
  hexcolor: ^2.0.5
  connectivity: ^3.0.6
  get:
  flutter_bloc: ^8.0.1
  #  screen_utils: ^0.0.1
  flutter_screenutil: ^5.5.3+2
  smooth_page_indicator: ^1.0.0+2
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  #  carousel_slider: ^4.1.1
  transparent_image: ^2.0.0
  device_preview: ^1.1.0
  translator: ^0.1.7
  pin_code_fields: ^7.4.0
  card_swiper: ^2.0.4
  cached_network_image:
  # firebase
  firebase_core: ^2.1.0
  firebase_messaging: ^14.0.0
  firebase_analytics: ^10.0.0
  cloud_firestore: ^4.0.0
  firebase_dynamic_links: ^5.0.0
  auto_size_text: ^3.0.0
  flutter_svg: ^1.0.3
  lottie: ^1.2.2
  google_translator:
  easy_localization: ^3.0.0
  carousel_slider: ^4.0.0
  image_picker: ^0.8.5+3
  material_dialogs: ^1.1.1
  flutter_phoenix: ^1.0.0
  geocoding:
  geolocator:
  google_maps_flutter: ^2.0.11
  readmore: ^2.2.0
  flutter_phone_direct_caller: ^2.1.1
#  pinput: ^2.2.0
  flutter_rating_bar: ^4.0.1
  flutter_local_notifications: ^11.0.1
  ## smart_select: ^4.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/svg/
    - assets/lottie/
    - assets/translations/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500